### ISSUE TITLE
BHT-002 WiFi Thermostat WiFi Issue

### ISSUE THREAD

**Issue by megagenio** [fashberg/WThermostatBeca#143]
Occasionally device loses wifi connection and is no longer reachable. I expected it to switch to AP mode in ordder to allow a device reboot but that doesn't happen. 
The only option in this case is to turn off the power and turn on again. 
Has this happened to anyone? 
Is there a manual procedure to force a reboot without having to act on the power supply?

**Comment by megagenio** [comment]
My router and thermostat are placed in front of each other at a distance of 3 meters with no obstacles in between. 
I have done all the tests but I have not been able to reproduce the problem. 
I believe that it is not a problem of losing the wifi connection but that for some reason the firmware crashes. 
The device remains connected to the network but does not execute commands. 
Since I have installed three BHT-002 WiFi Thermostat and this is the only one that shows this problem I think it is necessary to refresh the firmware.
But I thought it existed a manual procedure to force a reboot without having to act on the power supply.

**Comment by rumoldus** [comment]
I had the same issue too. BHT would not communicate but not revert to AP either. Only a power cycle would help. Meaning shutting down half of the house. For other reasons, I changed my Wifi router (now it is a Fritzbox) and it seems the problem has disappeared.

**Comment by SloppolS** [comment]
I have the same issue for month now. 
I have 5 Thermostats and all shows this behavior in the same moment. 
Most of the time 2-3 Thermostats lost wifi and I have to reconnect them in my Unifi Controller.

I can also see the issue in the wifi connection history.  Sometimes it starts to get worse and then disconnects, sometimes it disconnects  immediately

All other devices on the same access point have no issues.

![image](https://user-images.githubusercontent.com/92176396/151001998-ff0019a8-34d5-4f8b-8eac-a61711dbb652.png)
![image](https://user-images.githubusercontent.com/92176396/151002043-fd0de7a4-57c9-4e60-9763-e9693711481b.png)

**Comment by greegb** [comment]
I have the same problem, after some time (last time it was probably few weeks) thermostat becomes inaccesible in Home Assistant and via it's ip address. Only fix is to power off and power on again.

Manual operation through thermostat's panel works normally. It seems that WiFi module is losing connection with access point or maybe it freezes (I'm using Openwrt routers with 802.11r roaming but probably it doesn't matter).

I think that the issue may be caused by power cycling too fast the floor heating relay when floor temperature reaches it's limit (I've set mine to 40 degrees C). Sometimes the relay is constantly turning on and off which is not good. Any ideas how to fix it?

When I checked last mqtt messages before freezing I saw that floor temperature was at it's maximum limit which I've set.

I don't know how the stock firmware works but maybe there should be another hysteresis for floor temperature sensor (for example 2 degrees between turning on and off).

**Comment by stav242** [comment]
i got around the 2c hysteresis, by using a virtual PID thermostat in HA, it
uses the temp sensor and output to control of wThermostat - but does not
rely on the Wthermostat to make the on/off based on temp control. moves the
control logic to a virtual PID thermostat which works better.

**Comment by kolossboss** [comment]
I have the same issue. 
Also with unifi devices. I have 6 Thermostats and 2-3 of them loses connection in the same moment. This happened every few days/weeks.

Very strange. I have a lot of wifi devices(~50) and non of them show similar behaviours.

**Comment by paulius2k** [comment]
same as https://github.com/fashberg/WThermostatBeca/issues/127

**Comment by donivan2004** [comment]
You can try this solution https://github.com/fashberg/WThermostatBeca/issues/193 it works for me.
