### ISSUE TITLE
saving Thermostat 1.14-fas -> Relais connected to GPIO Inputs > Heating will not be saved

### ISSUE THREAD

**Issue by ilkkaolavas** [fashberg/WThermostatBeca#20]
Hi!

When I try to save saving Thermostat 1.14-fas -> Relais connected to GPIO Inputs > Heating on GPIO5 and save config and when I go back after restart I don't see that saved. Propably it is, but config does not save it correctly to be shown as saved. Worked on 1.12 but not 1.14.

Ilkka

**Comment by fashberg** [comment]
Hey @ilkkaolavas!

OK, i should solder the resistors in my new test-device to also be able to test this in real.

I had commented out the two lines reading the Hardware-Hack-Settings for debugging and forgot to reenable.

Fixed with some other issues at https://github.com/fashberg/WThermostatBeca/releases/tag/v1.15-fas 

Kind Regards
Folke

**Comment by ilkkaolavas** [comment]
Downgraded back to 1.12. Upgraded again from 1.12 -> 1.15. 
Config upgraded perfectly! 
Relay reading works perfectly!
Thanks!
