### ISSUE TITLE
Use the led to report state

### ISSUE THREAD

**Issue by adrez99** [fashberg/WThermostatBeca#34]
This is not a bug, but a request: is it possible to turn off the led if the thermostat is off?
Don't know if the led is connected to the MCU or the ESP, and if it's feasible, but it would be nice

**Comment by fashberg** [comment]
Hey @adrez99,

see: https://github.com/fashberg/WThermostatBeca#hardware

Because WThermostat runs only in WiFi-Chip and not on main CPU (MCU) and because of very limited commandset on the serial connection between both Chips it's not possible to take control of all functions of the device!

Kind Regards
Folke

**Comment by adrez99** [comment]
Oh that's a shame, thank you anyway
