### ISSUE TITLE
[Feature Request] LED Control

### ISSUE THREAD

**Issue by thundergreen** [fashberg/WThermostatBeca#58]
I dunno if it's possible at all but when we lay in bed we see this bright LED lighting all nightlong and were wondering if it would be possible to turn the LED off?

**Comment by fashberg** [comment]
Hey @thundergreen 

this is again category "not possible, because of MCU controlled" (https://github.com/fashberg/WThermostatBeca#can-you-add-xxx-as-a-feature)

We also have one thermostat in bedroom and it's not too light for us. 

You can desolder the LED or try to change resistor R19 (102=1 kΩ) to a higher value (*UNTESTED !!!*)
The Sping is for capacitive detection of Key 0 and must not be desoldered. 

Or try to use some sticky tape - stick inside the housing so no one will see. (*UNTESTED !!!*)

The buttons are glued to the board. So after you have removed the 4 screws and opened the main housing you can carefully lift up the board from the case.


![2020-11-01_16h33_26](https://user-images.githubusercontent.com/3075214/97807279-349bdc80-1c60-11eb-8cbb-c5833558c916.png)
![2020-11-01_16h34_12](https://user-images.githubusercontent.com/3075214/97807280-35cd0980-1c60-11eb-8c27-51a37ce11979.png)
![2020-11-01_16h34_48](https://user-images.githubusercontent.com/3075214/97807281-3665a000-1c60-11eb-8d03-d8efc8395944.png)



Kind Regards
Folke
